# Generated by Django 6.0.3 on 2026-03-30 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(verbose_name='Тапсырыс құрамы')),
                ('total_price', models.IntegerField(verbose_name='Жалпы сома')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Мекенжай')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('pending', 'Күтілуде'), ('confirmed', 'Қабылданды'), ('delivered', 'Жеткізілді'), ('cancelled', 'Болдырылмады')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Тапсырыс уақыты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыстар',
            },
        ),
    ]
