# Generated by Django 6.0.3 on 2026-03-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тағам аты')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('price', models.IntegerField(verbose_name='Бағасы')),
                ('category', models.CharField(choices=[('main', 'Негізгі тағам'), ('salad', 'Салат'), ('soup', 'Сорпа'), ('dessert', 'Десерт'), ('drink', 'Сусын')], max_length=100, verbose_name='Категория')),
                ('is_available', models.BooleanField(default=True, verbose_name='Қолжетімді')),
            ],
            options={
                'verbose_name': 'Тағам',
                'verbose_name_plural': 'Тағамдар',
            },
        ),
    ]
